services:
    nginx:
        image: nginx:latest
        ports:
            - 84:80
        volumes:
            - ./nginx/conf.d:/etc/ngnix/conf.d
        depends_on:
            - frontend
            - awm_django_app

    pgadmin4:
        image: dpage/pgadmin4
        ports:
            - 20080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: c21436494@tudublin.ie
            PGADMIN_DEFAULT_PASSWORD: password123
        #volumes:
        #  - my_pgadmin4_data:/var/lib/postgresql/data
        depends_on:
            - postgis

    postgis:
        image: kartoza/postgis:latest
        ports:
            - 25432:5432
        environment:
            POSTGRES_DB: gis
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        #volumes:
        #  - my_first_spatialdb_data:/var/lib/postgresql/data

    awm_django_app:
        image: geodjango_tutorial_image
        ports:
            - 8001:8001
        #build: .
        command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
        restart: always
        volumes:
            - .:/app
        depends_on:
            - postgis
    
    frontend:
        image: ianhipolito659/frontend_image:latest
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        depends_on:
            - awm_django_app